---
title: "Portfolio 8"
author: "Rachel Good"
date: "`r Sys.Date()`"
---

The purpose of this portfolio is to remake the Blackjack Game from my python class.

Python code:
import random

player_name = input("Enter player name:")
dealer_name = input("Enter dealer name:")

num_rounds = int(input("Enter number of rounds:"))
i = 1
while i <= num_rounds:
  player_card1 = random.randint(1,11)
  player_card2 = random.randint(1,11)

  dealer_card1 = random.randint(1,11)
  dealer_card2 = random.randint(1,11)

  player_counter = player_card1 + player_card2
  dealer_counter = dealer_card1 + dealer_card2

  print("Player:", player_counter, "Dealer:", dealer_counter)

  player_move = input("hit or stand?")
  while player_move == "hit":
    player_card_add = random.randint(1,11)
    print(player_name, "drew", player_card_add)
    player_counter += player_card_add
    print("Player:", player_counter)
    player_move = input("hit or stand?")
    

  while dealer_counter < 17:
    dealer_card_add = random.randint(1,11)
    print(dealer_name, "drew", dealer_card_add)
    dealer_counter += dealer_card_add
    print("Dealer:", dealer_counter)

  if player_counter == 21:
    print(player_name, "wins")
  elif player_counter > 21:
    print(dealer_name, "wins")
  elif dealer_counter > 21:
    print(dealer_name, "busts,", player_name, "wins")
  elif player_counter > dealer_counter and player_counter <= 21:
    print(player_name, "wins")
  elif dealer_counter > player_counter and dealer_counter <= 21:
      print(dealer_name, "wins")
  i += 1
  player_counter = 0
  dealer_counter = 0
  


So, this didn't end up accepting a hit or stand input... but this was the best I could get in a reasonable amount of time spent on this portfolio.
```{r blackjack}
player_name <- readline(prompt("Enter Player's Name:"))
dealer_name <- readline(prompt("Enter Dealer's Name:"))

num_rounds <- readline(prompt("Enter the number of rounds you wish to play:"))
num_rounds <- as.integer(num_rounds)

i<- 1
while (i < num_rounds) {
  p_card1 <- sample(1:11, 1)
  p_card2 <- sample(1:11, 1)
  p_counter <- p_card1 + p_card2
  
  d_card1 <- sample(1:11, 1)
  d_card2 <- sample(1:11, 1)
  d_counter <- d_card1 + d_card2
  
  output <- c("Player:", p_counter, "Dealer", d_counter)
  print(output)
  
  p_move <- readline(prompt("Enter hit or stand:"))
  while (p_move == "hit") {
    p_card_add <- sample(1:11, 1)
    p_output <- c("Player drew", p_card_add)
    print(p_output)
    p_counter <- p_counter + p_card_add
    p_output2 <- c("New player total:", p_counter)
    p_move <- readline(prompt("Enter hit or stand:"))
  }
  
  while (d_counter < 17) {
    d_card_add <- sample(1:11, 1)
    d_output <- c("Dealer drew", d_card_add)
    print(d_output)
    d_counter <- d_counter + d_card_add
    d_output2 <- c("New dealer total:", d_counter)
  }
  if (p_counter == 21){
  result1 <- c(player_name, "wins")
  print(result1)
    } else if (p_counter > 21) {
      result2 <- c(dealer_name, "wins")
      print(result2)
    } else if (d_counter > 21) {
      result3 <- c(dealer_name, "busts,", player_name, "wins")
      print(result3)
    } else if ((p_counter > d_counter)&(p_counter <= 21)) {
      result4 <- c(player_name, "wins")
      print(result4)
    } else if ((d_counter > p_counter)&(d_counter <= 21)) {
      result5 <- c(dealer_name, "wins")
      print(result5)
  }
  i <- i + 1
  p_counter <- 0
  d_counter <- 0
}

```
